mysql:
  user: 'root'
  password: 'asdfasdf'
  host: localhost
  database: mememana
  port: 3306
  poolsize: 10
  connectionTimeout: 10000
  idleTimout: 600000
  maxLifetime: 7200000
manaRotTime: 30d
manaWaitTime: 30m
serverRestartOffset: 10h5m
maximumDailyMana: 10
pearlRefillAmount: 
  EXILE: 1
  PRISON: 1
pearlUpgradeAmount: 10
